---
abstract: 'Saves capture results to your own variables'
author:
  - "\"Josh ben Jore\" <jjore@cpan.org>"
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-NamedCaptures
provides:
  Regexp::NamedCaptures:
    file: lib/Regexp/NamedCaptures.pm
    version: 0.05
recommends:
  Params::Validate: 0
requires:
  Carp: 0
  Text::Balanced: 0
  perl: v5.7.1
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
